// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type CookieKey struct {
	ID        int32
	CreatedAt time.Time
	HashKey   []byte
	BlockKey  []byte
}

type FilterInstance struct {
	ID           int32
	UserID       uuid.UUID
	FilterListID int32
	FilterName   string
	Params       pgtype.JSONB
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
}

type FilterList struct {
	ID         int32
	UserID     uuid.UUID
	Token      uuid.UUID
	CreatedAt  time.Time
	Downloaded bool
}

type User struct {
	ID               int32
	Uuid             uuid.UUID
	CreatedAt        time.Time
	Email            string
	EmailConfirmed   bool
	PasswordHash     sql.NullString
	ConfirmSelector  sql.NullString
	ConfirmVerifier  sql.NullString
	RecoverySelector sql.NullString
	RecoveryVerifier sql.NullString
	RecoveryExpiry   sql.NullTime
}
